### ISSUE TITLE
[Questions] About emscripten development environment

### ISSUE THREAD

**Issue by irelance** [zhaohappy/libmedia#12]
What is the ```emscripten``` version?
Which git hash does the ```FFmpeg``` used? I found that the version ```n7.0.1-5-g939b26c0d5``` you are using, but no tag/branch in official repository.
And I can't compile with these options ```--enable-websimd128```, ```--disable-wasmatomic```  which you define in ffmpeg build scripts. Are you use your private modify version?
And the ```nodejs``` version

**Comment by zhaohappy** [comment]
ffmpeg is compiled with my fork version [ffmpeg](https://github.com/zhaohappy/FFmpeg/tree/libmedia7.0).  The version of emscripten I use is v3.1.47, any version higher than this should be OK. And the version of Node is v21.6.2, I think Node's version is no strict requirement.

**Comment by irelance** [comment]
Thanks. I finally remove the ```--xxxable-websimd128```, ```--xxxable-wasmatomic``` to complie them. 
Besides, the wasm is too big to use as a web media player. 
Maybe ffmpeg 5.1 is a better choice. decode/aac.wasm nearly 18MB(ffmpeg >= 6.0) and 2MB(ffmpeg 5.1)

**Comment by zhaohappy** [comment]
I also found this problem, but after analysis, it is because the compiled aac wasm has a large size of static data with all are zero, it can compressed into about 300kB for http request after gzip,  is the same as the one compiled by the lower version of ffmpeg, so it is not a big problem. In addition, if you want to compile a lower version of ffmpeg, you need to change the AVPacket, AVFrame, and AVCodecParameters struct in the typescript code to be consistent with lower version of ffmpeg.
